/**
 * Curated local emoji library.
 *
 * A hand-picked set of emoji organised into 20 categories (Popular, Smileys,
 * Emotions, Gestures, People, Animals, Food, Nature, Activities, Travel,
 * Objects, Technology, Education, Science, Creative, Finance, Time, Symbols,
 * Numbers, Space), each with search keywords (including the category label
 * itself so "nature" finds nature emoji). Everything is stored/cached locally
 * — nothing is fetched.
 *
 * Recency + frequency history lives in localStorage so it survives reloads
 * and is cheap to read on every picker open.
 */
import { normalize } from "./util";

export interface EmojiEntry {
  char: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  label: string;
  emojis: EmojiEntry[];
}

const E = (char: string, keywords: string): EmojiEntry => ({ char, keywords: keywords.split(" ") });

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "popular",
    label: "Popular",
    emojis: [
      E("😀", "smile happy grin"),
      E("😂", "lol laugh joy tears"),
      E("😅", "sweat smile nervous"),
      E("😊", "smile blush happy"),
      E("😍", "love heart eyes adore"),
      E("😎", "cool sunglasses chill"),
      E("🥳", "party celebrate birthday"),
      E("🤔", "thinking ponder hmm"),
      E("😭", "sob cry tears"),
      E("🥰", "love adore cute"),
      E("👍", "thumbs up yes approve"),
      E("👎", "thumbs down no disapprove"),
      E("🙏", "pray please thank you bow"),
      E("👏", "clap applause praise"),
      E("🙌", "hands raised celebrate"),
      E("💪", "flex bicep strong muscle"),
      E("❤️", "heart love red"),
      E("🔥", "fire hot lit"),
      E("✨", "sparkles shiny magic"),
      E("💯", "hundred perfect full marks"),
      E("✅", "check done complete yes"),
      E("⭐", "star favorite top"),
      E("🎉", "party popper celebrate"),
      E("🚀", "rocket launch space fast"),
      E("💡", "bulb idea light"),
      E("🫶", "heart hands love"),
    ],
  },
  {
    id: "smileys",
    label: "Smileys",
    emojis: [
      E("😀", "smile happy grin"),
      E("😄", "smile laugh joy open"),
      E("😁", "beaming grin smile"),
      E("😂", "lol laugh joy tears"),
      E("🤣", "laugh rolling floor"),
      E("😊", "smile blush happy"),
      E("😇", "smile innocent angel halo"),
      E("🙂", "smile slight"),
      E("🙃", "upside down silly"),
      E("😉", "wink cheeky flirt"),
      E("😌", "relieved calm content"),
      E("😍", "love heart eyes adore"),
      E("🥰", "love adore cute"),
      E("😘", "kiss blow kissy"),
      E("😋", "yummy delicious savor"),
      E("😛", "tongue silly playful"),
      E("😜", "wink tongue silly"),
      E("🤪", "crazy zany wild"),
      E("🤑", "money mouth rich"),
      E("🤗", "hug open arms warm"),
      E("🤭", "giggle cover mouth shy"),
      E("🤫", "shush quiet hush"),
      E("🤔", "thinking ponder hmm"),
      E("🫠", "melting face"),
      E("😏", "smirk sly"),
      E("😒", "unamused annoyed"),
      E("😞", "disappointed sad"),
      E("😔", "pensive thoughtful sad"),
      E("😟", "worried concern"),
      E("😕", "confused unsure"),
      E("😢", "cry sad tear"),
      E("😭", "sob cry tears"),
      E("😤", "triumph steam frustrated"),
      E("😠", "angry mad"),
      E("😡", "angry rage mad"),
      E("🤯", "mind blown explosion"),
      E("😳", "flushed embarrassed"),
      E("🥺", "pleading puppy eyes"),
      E("😱", "scream shocked horrified"),
      E("😴", "sleepy tired"),
      E("🤤", "drooling hungry"),
      E("😪", "sleepy tired"),
      E("😮", "surprised wow"),
      E("🤐", "zipper mouth quiet"),
      E("😷", "mask sick cough"),
      E("🤒", "thermometer ill sick"),
      E("🤕", "bandage hurt injured"),
      E("🤢", "nauseated sick vomit"),
      E("🤧", "sneeze sniffle"),
      E("🥱", "yawn tired sleepy"),
      E("😎", "cool sunglasses chill"),
      E("🤓", "nerd glasses geek"),
      E("🧐", "monocle inspect curious"),
      E("🤠", "cowboy hat western"),
      E("🥳", "party celebrate birthday"),
      E("😺", "cat smile happy"),
      E("😸", "cat laugh joy"),
      E("😻", "cat love heart eyes"),
      E("🙀", "cat scream shocked"),
    ],
  },
  {
    id: "emotions",
    label: "Emotions",
    emojis: [
      E("❤️", "heart love red"),
      E("🧡", "heart orange"),
      E("💛", "heart yellow"),
      E("💚", "heart green"),
      E("💙", "heart blue"),
      E("💜", "heart purple"),
      E("🖤", "heart black"),
      E("🤍", "heart white"),
      E("🤎", "heart brown"),
      E("💔", "broken heart sad"),
      E("❣️", "heart exclamation"),
      E("💕", "two hearts love"),
      E("💞", "revolving hearts"),
      E("💓", "beating heart"),
      E("💗", "growing heart"),
      E("💖", "sparkling heart"),
      E("💘", "cupid heart arrow"),
      E("💝", "heart ribbon gift"),
      E("💟", "heart decoration"),
      E("☮️", "peace symbol"),
      E("❤️‍🔥", "heart fire passion"),
      E("🥹", "tear joy touched"),
      E("😻", "cat heart eyes"),
      E("💋", "kiss lips mark"),
      E("😤", "frustrated steam"),
    ],
  },
  {
    id: "gestures",
    label: "Gestures",
    emojis: [
      E("👍", "thumbs up yes approve"),
      E("👎", "thumbs down no disapprove"),
      E("👌", "ok okay perfect"),
      E("🤌", "pinched fingers chef kiss"),
      E("🤞", "fingers crossed luck"),
      E("🤟", "rock on love you"),
      E("🤘", "sign of horns rock"),
      E("🤙", "call me shaka"),
      E("👈", "point left"),
      E("👉", "point right"),
      E("👆", "point up"),
      E("👇", "point down"),
      E("☝️", "point up index"),
      E("✋", "hand raised stop high five"),
      E("🤚", "backhand raised"),
      E("🖐️", "hand fingers spread"),
      E("🖖", "vulcan salute"),
      E("👋", "wave hello goodbye"),
      E("🤏", "pinching small"),
      E("✌️", "peace victory two fingers"),
      E("🫰", "fingers heart"),
      E("🤝", "handshake agree deal"),
      E("👏", "clap applause praise"),
      E("🙌", "hands raised celebrate"),
      E("🫶", "heart hands love"),
      E("🤲", "palms together"),
      E("💪", "flex bicep strong muscle"),
      E("🤜", "fist right punch"),
      E("🤛", "fist left punch"),
      E("✊", "fist raised solidarity"),
      E("👊", "fist bump"),
      E("🫡", "salute respect"),
      E("🙏", "pray please thank you bow"),
    ],
  },
  {
    id: "people",
    label: "People",
    emojis: [
      E("👤", "person silhouette"),
      E("👥", "people group bust"),
      E("🧑", "adult person"),
      E("👩", "woman lady"),
      E("👨", "man"),
      E("🧒", "child kid"),
      E("👦", "boy"),
      E("👧", "girl"),
      E("👶", "baby infant"),
      E("🧓", "older adult"),
      E("👴", "old man grandpa"),
      E("👵", "old woman grandma"),
      E("👮", "police officer"),
      E("🕵️", "detective spy"),
      E("👷", "worker construction"),
      E("🤴", "prince"),
      E("👸", "princess"),
      E("👰", "bride wedding"),
      E("🤵", "groom tuxedo"),
      E("🎅", "santa claus christmas"),
      E("🤶", "mrs claus"),
      E("🦸", "superhero"),
      E("🦹", "supervillain"),
      E("🧙", "wizard mage"),
      E("🧚", "fairy"),
      E("🧛", "vampire"),
      E("🧜", "mermaid merman"),
      E("🧝", "elf"),
      E("🧟", "zombie"),
      E("🧑‍🍳", "chef cook"),
      E("🧑‍🏫", "teacher professor"),
      E("🧑‍🎓", "student graduate"),
      E("🧑‍💻", "developer coder"),
      E("🧑‍🚀", "astronaut"),
      E("🧑‍🔧", "mechanic"),
      E("🧑‍🌾", "farmer"),
      E("🧑‍⚕️", "doctor medic"),
      E("🧑‍🎤", "singer"),
      E("🧑‍🎨", "artist painter"),
      E("🧑‍🚒", "firefighter"),
      E("💃", "dancer woman"),
      E("🕺", "dancer man"),
    ],
  },
  {
    id: "animals",
    label: "Animals",
    emojis: [
      E("🐶", "dog puppy pet"),
      E("🐱", "cat kitty pet"),
      E("🐭", "mouse rat"),
      E("🐹", "hamster pet"),
      E("🐰", "rabbit bunny"),
      E("🦊", "fox sly"),
      E("🐻", "bear"),
      E("🐼", "panda"),
      E("🐨", "koala"),
      E("🐯", "tiger"),
      E("🦁", "lion king"),
      E("🐮", "cow"),
      E("🐷", "pig"),
      E("🐸", "frog"),
      E("🐵", "monkey face"),
      E("🙈", "see no evil monkey"),
      E("🙉", "hear no evil monkey"),
      E("🙊", "speak no evil monkey"),
      E("🐒", "monkey"),
      E("🐔", "chicken hen"),
      E("🐧", "penguin"),
      E("🐦", "bird"),
      E("🦆", "duck"),
      E("🦉", "owl night wise"),
      E("🦅", "eagle bird"),
      E("🦜", "parrot bird"),
      E("🐢", "turtle tortoise"),
      E("🐍", "snake"),
      E("🦎", "lizard"),
      E("🐊", "crocodile alligator"),
      E("🐆", "leopard"),
      E("🐅", "tiger"),
      E("🦓", "zebra"),
      E("🦍", "gorilla"),
      E("🦧", "orangutan"),
      E("🐘", "elephant"),
      E("🦛", "hippopotamus"),
      E("🦏", "rhinoceros"),
      E("🐪", "camel"),
      E("🦒", "giraffe"),
      E("🦘", "kangaroo"),
      E("🦙", "llama alpaca"),
      E("🐎", "horse"),
      E("🐖", "pig"),
      E("🐏", "ram sheep"),
      E("🐑", "sheep ewe"),
      E("🐐", "goat"),
      E("🦌", "deer"),
      E("🐕", "dog"),
      E("🐩", "poodle"),
      E("🦮", "guide dog"),
      E("🐈", "cat"),
      E("🦃", "turkey"),
      E("🦚", "peacock"),
      E("🦩", "flamingo"),
      E("🕊️", "dove peace"),
      E("🦝", "raccoon"),
      E("🦨", "skunk"),
      E("🦡", "badger"),
      E("🦫", "beaver"),
      E("🦥", "sloth"),
      E("🐿️", "chipmunk squirrel"),
      E("🦔", "hedgehog"),
      E("🐾", "paw prints animal"),
      E("🐉", "dragon"),
      E("🐲", "dragon face"),
    ],
  },
  {
    id: "food",
    label: "Food & Drink",
    emojis: [
      E("🍎", "apple fruit"),
      E("🍏", "green apple fruit"),
      E("🍐", "pear fruit"),
      E("🍊", "orange citrus fruit"),
      E("🍋", "lemon fruit citrus"),
      E("🍌", "banana fruit"),
      E("🍉", "watermelon fruit"),
      E("🍇", "grapes fruit"),
      E("🍓", "strawberry fruit berry"),
      E("🫐", "blueberry fruit"),
      E("🍒", "cherry fruit"),
      E("🍑", "peach fruit"),
      E("🥭", "mango fruit"),
      E("🍍", "pineapple fruit"),
      E("🥥", "coconut fruit"),
      E("🥝", "kiwi fruit"),
      E("🍅", "tomato"),
      E("🍆", "eggplant"),
      E("🥑", "avocado"),
      E("🥦", "broccoli vegetable"),
      E("🥬", "lettuce leafy green"),
      E("🥕", "carrot vegetable"),
      E("🌽", "corn maize"),
      E("🥔", "potato"),
      E("🍞", "bread toast"),
      E("🥐", "croissant pastry"),
      E("🥯", "bagel bread"),
      E("🧀", "cheese dairy"),
      E("🥚", "egg"),
      E("🍳", "fried egg cooking"),
      E("🥞", "pancakes breakfast"),
      E("🧇", "waffle"),
      E("🥓", "bacon"),
      E("🥩", "steak meat"),
      E("🍗", "chicken drumstick"),
      E("🍖", "meat bone"),
      E("🌭", "hot dog sausage"),
      E("🍔", "burger hamburger food"),
      E("🍟", "fries french"),
      E("🍕", "pizza food"),
      E("🥪", "sandwich"),
      E("🌮", "taco mexican"),
      E("🌯", "burrito wrap"),
      E("🥗", "salad healthy food"),
      E("🍝", "spaghetti pasta"),
      E("🍜", "noodles ramen"),
      E("🍲", "stew soup pot"),
      E("🍛", "curry rice"),
      E("🍣", "sushi"),
      E("🍱", "bento box"),
      E("🥟", "dumpling gyoza"),
      E("🍤", "fried shrimp tempura"),
      E("🍙", "rice ball onigiri"),
      E("🍚", "rice cooked"),
      E("🍦", "ice cream soft"),
      E("🍧", "shaved ice dessert"),
      E("🍨", "ice cream sundae"),
      E("🍰", "cake dessert birthday"),
      E("🎂", "birthday cake"),
      E("🧁", "cupcake dessert"),
      E("🍮", "custard pudding"),
      E("🍩", "donut doughnut"),
      E("🍪", "cookie biscuit"),
      E("🍫", "chocolate sweet"),
      E("🍿", "popcorn movie snack"),
      E("🧃", "juice drink box"),
      E("🥛", "milk glass"),
      E("☕", "coffee drink cafe"),
      E("🍵", "tea cup drink"),
      E("🧋", "bubble tea boba"),
      E("🥤", "soda drink cup"),
      E("🍺", "beer"),
      E("🍻", "beers cheers toast"),
      E("🥂", "clink glasses cheers toast"),
      E("🍷", "wine glass"),
      E("🍸", "cocktail martini"),
      E("🍹", "tropical drink"),
      E("🧉", "mate drink"),
      E("🍾", "champagne bottle toast"),
      E("🥜", "peanuts nuts"),
      E("🍯", "honey pot"),
    ],
  },
  {
    id: "nature",
    label: "Nature",
    emojis: [
      E("🌱", "sprout plant grow seed"),
      E("🌿", "herb leaf green"),
      E("🍀", "clover four leaf luck"),
      E("🍁", "maple leaf autumn"),
      E("🍂", "falling leaf autumn"),
      E("🍃", "leaf wind blowing"),
      E("🌾", "rice sheaf grain"),
      E("🌵", "cactus desert"),
      E("🌴", "palm tree beach"),
      E("🌳", "tree forest"),
      E("🌲", "pine tree evergreen"),
      E("🌸", "cherry blossom flower"),
      E("🌹", "rose flower"),
      E("🥀", "wilted flower"),
      E("🌺", "hibiscus flower"),
      E("🌻", "sunflower flower"),
      E("🌼", "blossom flower"),
      E("🌷", "tulip flower"),
      E("🌈", "rainbow colorful"),
      E("☀️", "sun bright warm"),
      E("🌞", "sun sunny shine"),
      E("🌙", "moon night"),
      E("☁️", "cloud weather"),
      E("🌧️", "rain cloud wet"),
      E("☔", "umbrella rain"),
      E("⛈️", "storm thunder rain"),
      E("🌨️", "snow cloud"),
      E("❄️", "snowflake winter cold"),
      E("☃️", "snowman winter"),
      E("⛄", "snowman snow"),
      E("🌊", "ocean wave water sea"),
      E("💧", "water drop droplet"),
      E("💨", "wind dash speed"),
      E("⭐", "star favorite top"),
      E("🌟", "glowing star shine"),
      E("✨", "sparkles shiny magic"),
      E("⚡", "zap lightning energy"),
      E("🔥", "fire hot lit"),
      E("💥", "collision explosion boom"),
      E("🌋", "volcano"),
      E("⛰️", "mountain peak"),
    ],
  },
  {
    id: "activities",
    label: "Activities",
    emojis: [
      E("⚽", "soccer football"),
      E("🏀", "basketball"),
      E("🏈", "american football"),
      E("⚾", "baseball"),
      E("🎾", "tennis"),
      E("🏐", "volleyball"),
      E("🏉", "rugby"),
      E("🎱", "billiards pool 8 ball"),
      E("🏓", "ping pong table tennis"),
      E("🏸", "badminton"),
      E("🥊", "boxing glove"),
      E("🥋", "martial arts karate"),
      E("🎽", "running shirt"),
      E("🎿", "ski skiing"),
      E("🏂", "snowboard"),
      E("🏋️", "weight lifting"),
      E("🤸", "cartwheel gymnastics"),
      E("⛹️", "basketball bounce"),
      E("🤾", "handball"),
      E("🏌️", "golf"),
      E("🏇", "horse racing"),
      E("🧘", "meditation yoga calm"),
      E("🏄", "surf surfing"),
      E("🏊", "swim swimming"),
      E("🤽", "water polo"),
      E("🚣", "row boat"),
      E("🧗", "climb climbing"),
      E("🚵", "mountain bike"),
      E("🚴", "cycling bike"),
      E("🏆", "trophy award"),
      E("🥇", "gold medal first"),
      E("🥈", "silver medal second"),
      E("🥉", "bronze medal third"),
      E("🏅", "medal sports"),
      E("🎖️", "military medal"),
      E("🎗️", "reminder ribbon"),
      E("🎫", "ticket event"),
      E("🎪", "circus tent"),
      E("🤹", "juggling"),
      E("🎭", "theater performing arts"),
      E("🎨", "art palette paint design"),
      E("🎬", "film movie clapper"),
      E("🎤", "mic microphone sing"),
      E("🎧", "headphones music listen"),
      E("🎼", "sheet music score"),
      E("🎹", "piano keyboard music"),
      E("🥁", "drum percussion"),
      E("🎷", "saxophone"),
      E("🎺", "trumpet"),
      E("🎸", "guitar music"),
      E("🎻", "violin"),
      E("🎲", "dice game"),
      E("🧩", "puzzle piece"),
      E("♟️", "chess strategy"),
      E("🎯", "target goal aim"),
      E("🎳", "bowling"),
      E("🎮", "video game controller play"),
      E("🎰", "slot machine casino"),
      E("📷", "camera photo picture"),
      E("🎥", "movie camera film"),
      E("📺", "tv television watch"),
    ],
  },
  {
    id: "travel",
    label: "Travel",
    emojis: [
      E("✈️", "airplane plane flight travel"),
      E("🛫", "takeoff plane flight"),
      E("🛬", "landing plane"),
      E("🛩️", "small airplane"),
      E("💺", "seat plane"),
      E("🛰️", "satellite orbit"),
      E("🚀", "rocket launch space fast"),
      E("🛸", "flying saucer ufo alien"),
      E("🚁", "helicopter"),
      E("⛵", "sailboat"),
      E("🚤", "speedboat"),
      E("🛳️", "passenger ship cruise"),
      E("⚓", "anchor sea"),
      E("🧭", "compass navigate direction"),
      E("🏖️", "beach sun umbrella"),
      E("🏝️", "island beach vacation"),
      E("🏜️", "desert"),
      E("⛰️", "mountain peak"),
      E("🏔️", "mountain snow summit"),
      E("🏕️", "camping tent"),
      E("⛺", "tent camping outdoors"),
      E("🏠", "home house"),
      E("🏡", "house garden"),
      E("🏙️", "city skyline"),
      E("🏢", "office building"),
      E("🏨", "hotel"),
      E("🏛️", "classical building museum"),
      E("⛪", "church"),
      E("🕌", "mosque"),
      E("🗺️", "map world atlas"),
      E("🗾", "japan map"),
      E("🌍", "globe earth world"),
      E("🌎", "globe americas earth"),
      E("🌏", "globe asia earth"),
      E("🚗", "car auto drive"),
      E("🚕", "taxi cab"),
      E("🚙", "suv jeep"),
      E("🚌", "bus"),
      E("🚓", "police car"),
      E("🚑", "ambulance"),
      E("🚒", "fire engine"),
      E("🚐", "minibus van"),
      E("🚚", "truck delivery"),
      E("🚜", "tractor"),
      E("🛵", "scooter"),
      E("🏍️", "motorcycle"),
      E("🚲", "bicycle bike cycle"),
      E("🛴", "kick scooter"),
      E("🚏", "bus stop"),
      E("🎢", "roller coaster amusement"),
      E("🧳", "luggage suitcase travel"),
    ],
  },
  {
    id: "objects",
    label: "Objects",
    emojis: [
      E("📝", "memo note pencil writing"),
      E("📌", "pushpin pin keep"),
      E("📁", "folder organize files"),
      E("🗂️", "card index dividers organize"),
      E("📅", "calendar date schedule"),
      E("📆", "calendar tear off"),
      E("🗓️", "spiral calendar plan"),
      E("📎", "paperclip attach"),
      E("✂️", "scissors cut"),
      E("🔒", "lock closed secure private"),
      E("🔓", "unlock open"),
      E("🔑", "key access pass"),
      E("💾", "floppy disk save storage"),
      E("📚", "books library study"),
      E("📖", "open book read story"),
      E("🗒️", "spiral notepad notes"),
      E("📋", "clipboard checklist"),
      E("📦", "package box parcel"),
      E("📷", "camera photo picture"),
      E("📸", "camera flash photo"),
      E("📹", "video camera record"),
      E("📞", "telephone phone call"),
      E("☎️", "telephone classic"),
      E("📻", "radio"),
      E("🕰️", "mantelpiece clock"),
      E("⏰", "alarm clock time wake"),
      E("⌛", "hourglass time"),
      E("🔋", "battery charge"),
      E("🔌", "plug electric"),
      E("💡", "bulb idea light"),
      E("🔦", "flashlight torch"),
      E("🕯️", "candle light"),
      E("💰", "money bag cash"),
      E("💎", "gem diamond jewel"),
      E("⚖️", "scale balance justice"),
      E("🧰", "toolbox tools"),
      E("🔧", "wrench tool"),
      E("🔨", "hammer tool"),
      E("🛠️", "hammer wrench tools"),
      E("🔩", "nut bolt screw"),
      E("⚙️", "gear settings cog"),
      E("🧱", "brick building"),
      E("⛓️", "chains link"),
      E("🧲", "magnet"),
      E("🔪", "kitchen knife"),
      E("🗡️", "dagger knife"),
      E("⚔️", "crossed swords"),
      E("🛡️", "shield protect"),
      E("🔮", "crystal ball fortune"),
      E("📿", "prayer beads"),
      E("💈", "barber pole"),
      E("🔭", "telescope astronomy"),
      E("🔬", "microscope science"),
      E("🕳️", "hole"),
      E("🚪", "door"),
      E("🪑", "chair"),
      E("🛏️", "bed sleep"),
      E("🛋️", "couch sofa"),
      E("🚿", "shower"),
      E("🛁", "bathtub bath"),
      E("🧴", "lotion bottle"),
      E("🧹", "broom clean"),
      E("🧻", "toilet paper"),
      E("🧼", "soap clean"),
      E("🪥", "toothbrush"),
      E("🧽", "sponge clean"),
      E("🛒", "shopping cart trolley"),
      E("🩹", "bandage first aid"),
      E("💊", "pill medicine"),
      E("💉", "syringe vaccine needle"),
      E("👑", "crown royalty"),
      E("💍", "ring diamond engagement"),
      E("⌚", "watch time"),
    ],
  },
  {
    id: "technology",
    label: "Technology",
    emojis: [
      E("💻", "laptop computer"),
      E("🖥️", "desktop computer"),
      E("⌨️", "keyboard typing"),
      E("🖱️", "mouse computer"),
      E("🖲️", "trackball computer"),
      E("🕹️", "joystick game"),
      E("💽", "minidisc storage"),
      E("💾", "floppy disk save"),
      E("💿", "cd optical disc"),
      E("📀", "dvd disc"),
      E("📼", "videotape vhs"),
      E("📱", "smartphone mobile phone"),
      E("📲", "phone with arrow"),
      E("🔋", "battery charge"),
      E("🔌", "plug power"),
      E("🖨️", "printer"),
      E("📟", "pager"),
      E("📠", "fax machine"),
      E("📡", "satellite antenna"),
      E("📺", "tv television"),
      E("🎙️", "studio microphone"),
      E("🎚️", "level slider"),
      E("🎛️", "control knobs"),
      E("🧮", "abacus calculator"),
      E("🖧", "network computer"),
      E("📷", "camera"),
      E("📸", "camera flash"),
      E("🎥", "movie camera"),
      E("📻", "radio"),
    ],
  },
  {
    id: "education",
    label: "Education",
    emojis: [
      E("🎒", "backpack school"),
      E("📚", "books library study"),
      E("📖", "open book read"),
      E("📕", "closed book red"),
      E("📗", "green book"),
      E("📘", "blue book"),
      E("📙", "orange book"),
      E("📔", "notebook decorative"),
      E("📓", "notebook"),
      E("📒", "ledger notebook"),
      E("📃", "page curl document"),
      E("📜", "scroll ancient"),
      E("📄", "document file page"),
      E("📰", "newspaper news"),
      E("📑", "bookmark tabs"),
      E("🔖", "bookmark"),
      E("🏷️", "label tag"),
      E("✏️", "pencil writing"),
      E("✒️", "fountain pen"),
      E("🖋️", "pen nib"),
      E("🖊️", "pen ballpoint"),
      E("🖌️", "paintbrush"),
      E("🖍️", "crayon"),
      E("📝", "memo note"),
      E("📐", "triangular ruler geometry"),
      E("📏", "straight ruler measure"),
      E("📌", "pushpin"),
      E("📍", "round pushpin location"),
      E("🖇️", "paperclips"),
      E("🗃️", "card file box"),
      E("🗄️", "file cabinet"),
      E("🗑️", "trash wastebin delete"),
      E("📋", "clipboard"),
      E("📁", "folder"),
      E("📂", "open folder"),
      E("🗂️", "card index"),
      E("🏫", "school"),
      E("🎓", "graduation cap degree"),
      E("🧑‍🎓", "student"),
      E("🧑‍🏫", "teacher"),
    ],
  },
  {
    id: "science",
    label: "Science",
    emojis: [
      E("🔬", "microscope science lab"),
      E("🧪", "test tube experiment lab"),
      E("🧫", "petri dish culture lab"),
      E("🧬", "dna gene biology"),
      E("⚗️", "alembic chemistry"),
      E("🧲", "magnet magnetic"),
      E("⚛️", "atom physics"),
      E("🔭", "telescope astronomy"),
      E("🛰️", "satellite space"),
      E("🧿", "nazar amulet"),
      E("💊", "pill medicine"),
      E("💉", "syringe"),
      E("🧠", "brain mind smart"),
      E("🫀", "anatomical heart"),
      E("🫁", "lungs breathe"),
      E("🦴", "bone skeleton"),
      E("🦷", "tooth dental"),
      E("👁️", "eye see vision"),
      E("👅", "tongue taste"),
      E("👂", "ear hear"),
      E("👃", "nose smell"),
      E("👄", "lips mouth"),
      E("🧬", "biology"),
      E("🧪", "chemistry"),
      E("📊", "bar chart data science"),
      E("🧮", "abacus math"),
    ],
  },
  {
    id: "creative",
    label: "Creative",
    emojis: [
      E("🎨", "art palette paint design"),
      E("🖌️", "paintbrush art"),
      E("🖍️", "crayon color"),
      E("🎭", "theater masks drama"),
      E("🎬", "movie clapper film"),
      E("🎤", "microphone sing"),
      E("🎧", "headphones music"),
      E("🎼", "sheet music score"),
      E("🎹", "piano keyboard"),
      E("🥁", "drum"),
      E("🎷", "saxophone jazz"),
      E("🎺", "trumpet"),
      E("🎸", "guitar"),
      E("🪕", "banjo"),
      E("🎻", "violin"),
      E("🎲", "dice"),
      E("🧩", "puzzle"),
      E("♟️", "chess"),
      E("🎯", "target"),
      E("🎮", "video game"),
      E("🎰", "slot machine"),
      E("📷", "camera photography"),
      E("🎥", "film camera"),
      E("🪁", "kite fly"),
      E("🎭", "performance"),
      E("💄", "lipstick makeup"),
      E("💍", "jewelry ring"),
      E("💼", "briefcase"),
      E("🧵", "thread sewing"),
      E("🧶", "yarn knitting"),
      E("👗", "dress fashion"),
      E("👔", "necktie suit"),
      E("👟", "sneaker shoe"),
      E("👒", "hat"),
      E("🧢", "cap baseball hat"),
      E("🎩", "top hat magic"),
      E("👓", "glasses spectacles"),
      E("🕶️", "sunglasses"),
      E("💃", "dance"),
      E("🕺", "dance"),
    ],
  },
  {
    id: "finance",
    label: "Finance",
    emojis: [
      E("💰", "money bag cash"),
      E("💴", "yen banknote"),
      E("💵", "dollar banknote"),
      E("💶", "euro banknote"),
      E("💷", "pound banknote"),
      E("💸", "money wings flying"),
      E("💳", "credit card"),
      E("🧾", "receipt bill"),
      E("🪙", "coin money"),
      E("💹", "chart rising yen growth"),
      E("📈", "chart increasing growth"),
      E("📉", "chart decreasing decline"),
      E("📊", "bar chart stats"),
      E("💼", "briefcase business"),
      E("🏦", "bank"),
      E("💱", "currency exchange"),
      E("💲", "heavy dollar sign"),
      E("🏧", "atm machine bank"),
      E("📉", "stock market"),
      E("🧮", "calculator"),
    ],
  },
  {
    id: "time",
    label: "Time",
    emojis: [
      E("⏰", "alarm clock time wake"),
      E("⌚", "watch time"),
      E("⏱️", "stopwatch timer"),
      E("⏲️", "timer clock"),
      E("⏳", "hourglass flowing"),
      E("⌛", "hourglass done"),
      E("🕰️", "mantelpiece clock"),
      E("🕐", "one o'clock"),
      E("🕑", "two o'clock"),
      E("🕒", "three o'clock"),
      E("🕓", "four o'clock"),
      E("🕔", "five o'clock"),
      E("🕕", "six o'clock"),
      E("🕖", "seven o'clock"),
      E("🕗", "eight o'clock"),
      E("🕘", "nine o'clock"),
      E("🕙", "ten o'clock"),
      E("🕚", "eleven o'clock"),
      E("🕛", "twelve o'clock"),
      E("🕜", "one thirty"),
      E("🕝", "two thirty"),
      E("🕞", "three thirty"),
      E("🕟", "four thirty"),
      E("🕠", "five thirty"),
      E("🕡", "six thirty"),
      E("🕢", "seven thirty"),
      E("🕣", "eight thirty"),
      E("🕤", "nine thirty"),
      E("🕥", "ten thirty"),
      E("🕦", "eleven thirty"),
      E("🕧", "twelve thirty"),
      E("📅", "calendar date"),
      E("🗓️", "calendar plan"),
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    emojis: [
      E("✅", "check done complete yes"),
      E("❌", "cross wrong no cancel"),
      E("❎", "cross button no"),
      E("➖", "minus subtract"),
      E("➕", "plus add"),
      E("➗", "divide"),
      E("✖️", "multiply x"),
      E("💯", "hundred perfect full marks"),
      E("✔️", "check mark yes"),
      E("☑️", "check box tick"),
      E("🔘", "radio button"),
      E("🔴", "red circle"),
      E("🟠", "orange circle"),
      E("🟡", "yellow circle"),
      E("🟢", "green circle"),
      E("🔵", "blue circle"),
      E("🟣", "purple circle"),
      E("⚫", "black circle"),
      E("⚪", "white circle"),
      E("🔶", "large orange diamond"),
      E("🔷", "large blue diamond"),
      E("🔸", "small orange diamond"),
      E("🔹", "small blue diamond"),
      E("🔺", "red triangle up"),
      E("🔻", "red triangle down"),
      E("♻️", "recycle green"),
      E("⚠️", "warning alert caution"),
      E("🚫", "prohibited no entry"),
      E("⛔", "no entry stop"),
      E("🚸", "children crossing"),
      E("☢️", "radioactive hazard"),
      E("♿", "wheelchair accessible"),
      E("♀️", "female symbol"),
      E("♂️", "male symbol"),
      E("⚕️", "medical symbol"),
      E("☮️", "peace"),
      E("⚛️", "atom"),
      E("🔁", "repeat arrows"),
      E("🔃", "clockwise arrows"),
      E("↔️", "left right arrow"),
      E("↕️", "up down arrow"),
      E("➡️", "right arrow"),
      E("⬅️", "left arrow"),
      E("⬆️", "up arrow"),
      E("⬇️", "down arrow"),
      E("⏩", "fast forward"),
      E("⏪", "rewind"),
      E("▶️", "play"),
      E("⏸️", "pause"),
      E("⏹️", "stop"),
      E("🔒", "lock"),
      E("🔓", "unlock"),
      E("♈", "aries zodiac"),
      E("♉", "taurus zodiac"),
      E("♊", "gemini zodiac"),
      E("♋", "cancer zodiac"),
      E("♌", "leo zodiac"),
      E("♍", "virgo zodiac"),
      E("♎", "libra zodiac"),
      E("♏", "scorpio zodiac"),
      E("♐", "sagittarius zodiac"),
      E("♑", "capricorn zodiac"),
      E("♒", "aquarius zodiac"),
      E("♓", "pisces zodiac"),
      E("⛎", "ophiuchus zodiac"),
      E("⚡", "zap lightning"),
      E("💤", "zzz sleep tired"),
      E("🎯", "target goal"),
      E("🕊️", "dove peace"),
    ],
  },
  {
    id: "numbers",
    label: "Numbers",
    emojis: [
      E("0️⃣", "zero number keycap"),
      E("1️⃣", "one number keycap"),
      E("2️⃣", "two number keycap"),
      E("3️⃣", "three number keycap"),
      E("4️⃣", "four number keycap"),
      E("5️⃣", "five number keycap"),
      E("6️⃣", "six number keycap"),
      E("7️⃣", "seven number keycap"),
      E("8️⃣", "eight number keycap"),
      E("9️⃣", "nine number keycap"),
      E("🔟", "ten keycap"),
      E("🔢", "input numbers"),
      E("🔢", "1234 number pad"),
      E("⏸️", "pause count"),
    ],
  },
  {
    id: "space",
    label: "Space",
    emojis: [
      E("🚀", "rocket launch space fast"),
      E("🛸", "flying saucer ufo alien"),
      E("🛰️", "satellite orbit"),
      E("🌕", "full moon"),
      E("🌖", "waning gibbous moon"),
      E("🌗", "last quarter moon"),
      E("🌘", "waning crescent moon"),
      E("🌑", "new moon"),
      E("🌒", "waxing crescent moon"),
      E("🌓", "first quarter moon"),
      E("🌔", "waxing gibbous moon"),
      E("🌚", "new moon face"),
      E("🌝", "full moon face"),
      E("🌛", "first quarter moon face"),
      E("🌜", "last quarter moon face"),
      E("🌍", "globe earth world"),
      E("🌎", "globe americas"),
      E("🌏", "globe asia"),
      E("🌌", "milky way galaxy night"),
      E("☄️", "comet shooting"),
      E("💫", "dizzy stars"),
      E("🌠", "shooting star"),
      E("⭐", "star"),
      E("🌟", "glowing star"),
      E("✨", "sparkles"),
      E("🔭", "telescope"),
      E("🪐", "ringed planet saturn"),
      E("🌙", "crescent moon night"),
    ],
  },
];

/** Every emoji flattened, with its category label added as a keyword. */
export const ALL_EMOJI: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) =>
  c.emojis.map((e) => ({ ...e, keywords: [...e.keywords, c.label.toLowerCase(), c.id] })),
);

const ALL_SET = new Map(ALL_EMOJI.map((e) => [e.char, e]));

/** Normalized search across char + keywords + category. */
export function searchEmoji(query: string): EmojiEntry[] {
  const q = normalize(query);
  if (!q) return ALL_EMOJI;
  return ALL_EMOJI.filter((e) => {
    if (e.char === q) return true;
    const words = e.keywords.join(" ").toLowerCase().replace(/[^\p{L}\p{N}\s]/gu, " ").replace(/\s+/g, " ").trim();
    return words.includes(q);
  });
}

// ---------------------------------------------------------------------------
// Recency / frequency history (localStorage)
// ---------------------------------------------------------------------------

const EMOJI_STORE_KEY = "locus:emoji-history";
const RECENT_LIMIT = 24;
const FREQUENT_LIMIT = 12;

interface EmojiHistory {
  recent: string[];
  counts: Record<string, number>;
}

function readHistory(): EmojiHistory {
  try {
    const raw = localStorage.getItem(EMOJI_STORE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw) as EmojiHistory;
      if (Array.isArray(parsed.recent) && typeof parsed.counts === "object" && parsed.counts) {
        return {
          recent: parsed.recent.filter((c) => typeof c === "string" && ALL_SET.has(c)).slice(0, RECENT_LIMIT),
          counts: parsed.counts,
        };
      }
    }
  } catch {
    /* ignore */
  }
  return { recent: [], counts: {} };
}

function writeHistory(h: EmojiHistory): void {
  try {
    localStorage.setItem(EMOJI_STORE_KEY, JSON.stringify(h));
  } catch {
    /* ignore */
  }
}

/** Record an emoji use (moves it to the front of recents, bumps frequency). */
export function recordEmojiUse(char: string): void {
  if (!ALL_SET.has(char)) return;
  const h = readHistory();
  h.recent = [char, ...h.recent.filter((c) => c !== char)].slice(0, RECENT_LIMIT);
  h.counts[char] = (h.counts[char] ?? 0) + 1;
  writeHistory(h);
}

/** Most recently used emoji, newest first. */
export function getRecentEmoji(): EmojiEntry[] {
  return readHistory().recent.map((c) => ALL_SET.get(c)!).filter(Boolean);
}

/** Most frequently used emoji, by usage count. */
export function getFrequentEmoji(): EmojiEntry[] {
  const h = readHistory();
  return Object.entries(h.counts)
    .filter(([c]) => ALL_SET.has(c))
    .sort((a, b) => b[1] - a[1])
    .slice(0, FREQUENT_LIMIT)
    .map(([c]) => ALL_SET.get(c)!)
    .filter(Boolean);
}
